# Generated by Django 6.0.7 on 2026-08-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
