# Generated by Django 6.0.7 on 2026-07-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_song_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics_pdf',
            field=models.FileField(default='lyrics/LYRIC_FILE_NOT_YET_UPLOADED.pdf', max_length=1000000000, upload_to='lyrics'),
        ),
    ]
